# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultquery < Formula
  desc "Query Obsidian vault files by YAML frontmatter"
  homepage "https://github.com/andinger/vaultquery"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/vaultquery/releases/download/v3.0.0/vaultquery_3.0.0_darwin_amd64.tar.gz"
      sha256 "c6f34f61dc6186e95c74285f60b258300b42bd498b5936be76fd140b50f88301"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/vaultquery/releases/download/v3.0.0/vaultquery_3.0.0_darwin_arm64.tar.gz"
      sha256 "1811bad77dcd5d9fe20a3dc1f0803451e7fd2018b87a4f87dea71322c5007057"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.0.0/vaultquery_3.0.0_linux_amd64.tar.gz"
      sha256 "dcddd6d4fae3bc1ba30b7ebe112f4d6876a4bcda7d2ecf12b190a5e7be57c2cf"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.0.0/vaultquery_3.0.0_linux_arm64.tar.gz"
      sha256 "2411c28453ff464c892b58e428e0b779fff2a32c5c9bd9e8f7a5251035ebf8a4"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  test do
    system bin/"vaultquery", "--version"
  end
end
