# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultquery < Formula
  desc "Query Obsidian vault files by YAML frontmatter"
  homepage "https://github.com/andinger/vaultquery"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/vaultquery/releases/download/v2.1.0/vaultquery_2.1.0_darwin_amd64.tar.gz"
      sha256 "4fef7cd8baae6fcc3bdeccbcaa5fa39dc47f60682e93c0268c0dbf86d1a07fc9"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/vaultquery/releases/download/v2.1.0/vaultquery_2.1.0_darwin_arm64.tar.gz"
      sha256 "46411867f3054d728f709e7c2736516a50ad11c972175f1fadf3563d4bff30cb"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v2.1.0/vaultquery_2.1.0_linux_amd64.tar.gz"
      sha256 "acc24065c8fdeff5532e73e21ebe88332cafe31ed24bae5a008911bab8e3d90d"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v2.1.0/vaultquery_2.1.0_linux_arm64.tar.gz"
      sha256 "f63271010dce286c401fa5fee0d46f681fa483d9b4780206f5aa3bd2a47a112c"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  test do
    system bin/"vaultquery", "--version"
  end
end
