# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultquery < Formula
  desc "Query Obsidian vault files by YAML frontmatter"
  homepage "https://github.com/andinger/vaultquery"
  version "3.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.3/vaultquery_3.1.3_darwin_amd64.tar.gz"
      sha256 "d7f1d9383da7cd01c89764e7d12c0b2f583c8baca41a043080e6f8fdf78d9568"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.3/vaultquery_3.1.3_darwin_arm64.tar.gz"
      sha256 "d4c2738f7570a6708ad03490d8fb2d958e3165b8124dc52f6906f2939bd3bc54"

      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.3/vaultquery_3.1.3_linux_amd64.tar.gz"
      sha256 "22cb6b97cfd5bbe4ecc881a994df8534cae68729ddd9e42f032eb195e010028b"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andinger/vaultquery/releases/download/v3.1.3/vaultquery_3.1.3_linux_arm64.tar.gz"
      sha256 "c9f7401268a99aafe31363bac5428d285388d6b4719e28acf607b478cc5551fc"
      define_method(:install) do
        bin.install "vaultquery"
      end
    end
  end

  test do
    system bin/"vaultquery", "--version"
  end
end
